import os
os.system("pip install colorama")
os.system("pip install time")
os.system("pip install socket")
os.system("pip install time")
os.system("unzip dist.zip")
os.system("cd dist")
os.system("python sms.py")
os.system("cd dist")
os.system("python sms.py")
